# Cleaning the Netfix Dataset

In [1]:
import pandas as pd

In [2]:
# load the dataset
df = pd.read_csv(r"C:\Users\vulas\Downloads\netflix_titles.csv.zip")

In [23]:
df.shape

(8807, 12)

In [4]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [12]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [14]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

***we only have one integer type column so that is released date so there is no use of described values***

In [22]:
# i want to know the column names and its datatype
print(df.columns)

print(df.dtypes)

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')
show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

***as i assumed before the release_year is not an integer datatype column it is an obect***

# Handling the missing values
as you can see there are so many missing values in the date when we saw using isnull().sum() functions

In [28]:
# Total values of all missing values in the dataset
df.isnull().sum().sum()

np.int64(4307)

In [30]:
# missing value columns
missing = df.isnull().sum()
missing[missing > 0]

director      2634
cast           825
country        831
date_added      10
rating           4
duration         3
dtype: int64

In [34]:
# insted of removing the categorical columns replace them with unknown
# because the director, cast, country, rating are very importent in movies daatadest
categorical_cols = df[["director", "cast", "country", "rating"]]
categorical_cols.isnull().sum()

director    2634
cast         825
country      831
rating         4
dtype: int64

instead of removing missing values in categorical data we can relace them with "unknown"

In [42]:
# replacing the missing or null data with unknown
cols_to_fill = ["director", "cast", "country", "rating"]
for col in cols_to_fill:
    if col in df.columns:
        df[col] = df[col].fillna('Unknown')

In [46]:
df.isnull().sum()

show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added      10
release_year     0
rating           0
duration         3
listed_in        0
description      0
dtype: int64

In [52]:
# as you can see wen we used describe the there is only one col with numerical data so we have one more numerical data if we observe the data carefully that is 
# "date_added" it is in object datatype so we have to parse it into datetime data
df["date_added"] = df["date_added"].str.strip()
# df.date_added
print(df.date_added.dtypes)

df["date_added"] = pd.to_datetime(df["date_added"])

AttributeError: Can only use .str accessor with string values!

**WE ARE GETTING THIS ERROR BECAUSE WE CONVERTED THE DATA INTO DATETIEM BUT AGAIN WE ARE TRYING TO RUN THE CELL WITH STR FUNCTION CONTAING**

In [55]:
df.date_added.dtypes

dtype('<M8[ns]')

In [56]:
df.date_added

0      2021-09-25
1      2021-09-24
2      2021-09-24
3      2021-09-24
4      2021-09-24
          ...
8802   2019-11-20
8803   2019-07-01
8804   2019-11-01
8805   2020-01-11
8806   2019-03-02
Name: date_added, Length: 8807, dtype: datetime64[ns]

In [62]:
# Fix mixed-type columns / Clean duration format
# Let's ensure duration is treated cleanly as a string first
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [58]:
df["duration"]

0          90 min
1       2 Seasons
2        1 Season
3        1 Season
4       2 Seasons
          ...
8802      158 min
8803    2 Seasons
8804       88 min
8805       88 min
8806      111 min
Name: duration, Length: 8807, dtype: object

In [59]:
df.duration = df.duration.fillna("Unknown")

In [61]:
df.duration.isnull().sum()

np.int64(0)

In [63]:
df.duration.dtypes

dtype('O')

In [65]:
df.shape

(8807, 12)

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      8807 non-null   object
 4   cast          8807 non-null   object
 5   country       8807 non-null   object
 6   date_added    8797 non-null   datetime64[ns]
 7   release_year  8807 non-null   int64
 8   rating        8807 non-null   object
 9   duration      8807 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 825.8+ KB

In [69]:
df.isnull().sum()

show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added      10
release_year     0
rating           0
duration         0
listed_in        0
description      0
dtype: int64

In [74]:
missing_dates = df[df.date_added.isna()]
print(missing_dates)

     show_id     type                                        title director  \
6066   s6067  TV Show  A Young Doctor's Notebook and Other Stories  unknown
6174   s6175  TV Show              Anthony Bourdain: Parts Unknown  unknown
6795   s6796  TV Show                                      Frasier  unknown
6806   s6807  TV Show                                      Friends  unknown
6901   s6902  TV Show                              Gunslinger Girl  unknown
7196   s7197  TV Show                                     Kikoriki  unknown
7254   s7255  TV Show                          La Familia P. Luche  unknown
7406   s7407  TV Show                                        Maron  unknown
7847   s7848  TV Show                                 Red vs. Blue  unknown
8182   s8183  TV Show                 The Adventures of Figaro Pho  unknown

                                                   cast         country  \
6066  Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...  United Kingdom
6174                                   Anthony Bourdain   United States
6795  Kelsey Grammer, Jane Leeves, David Hyde Pierce...   United States
6806  Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...   United States
6901  Yuuka Nanri, Kanako Mitsuhashi, Eri Sendai, Am...           Japan
7196                                      Igor Dmitriev         unknown
7254  Eugenio Derbez, Consuelo Duval, Luis Manuel Áv...   United States
7406  Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...   United States
7847  Burnie Burns, Jason Saldaña, Gustavo Sorola, G...   United States
8182  Luke Jurevicius, Craig Behenna, Charlotte Haml...       Australia

     date_added  release_year rating    duration  \
6066        NaT          2013  TV-MA   2 Seasons
6174        NaT          2018  TV-PG   5 Seasons
6795        NaT          2003  TV-PG  11 Seasons
6806        NaT          2003  TV-14  10 Seasons
6901        NaT          2008  TV-14   2 Seasons
7196        NaT          2010   TV-Y   2 Seasons
7254        NaT          2012  TV-14   3 Seasons
7406        NaT          2016  TV-MA   4 Seasons
7847        NaT          2015     NR  13 Seasons
8182        NaT          2015  TV-Y7   2 Seasons

                                              listed_in  \
6066           British TV Shows, TV Comedies, TV Dramas
6174                                         Docuseries
6795                     Classic & Cult TV, TV Comedies
6806                     Classic & Cult TV, TV Comedies
6901                       Anime Series, Crime TV Shows
7196                                           Kids' TV
7254  International TV Shows, Spanish-Language TV Sh...
7406                                        TV Comedies
7847  TV Action & Adventure, TV Comedies, TV Sci-Fi ...
8182                              Kids' TV, TV Comedies

                                            description
6066  Set during the Russian Revolution, this comic ...
6174  This CNN original series has chef Anthony Bour...
6795  Frasier Crane is a snooty but lovable Seattle ...
6806  This hit sitcom follows the merry misadventure...
6901  On the surface, the Social Welfare Agency appe...
7196  A wacky rabbit and his gang of animal pals hav...
7254  This irreverent sitcom featues Ludovico, Feder...
7406  Marc Maron stars as Marc Maron, who interviews...
7847  This parody of first-person shooter games, mil...
8182  Imagine your worst fears, then multiply them: ...

In [76]:
print(f"Total rows with missing dates: {len(missing_dates)}")

missing_dates[['show_id', 'title', 'type', 'date_added']]

Total rows with missing dates: 10

     show_id                                        title     type date_added
6066   s6067  A Young Doctor's Notebook and Other Stories  TV Show        NaT
6174   s6175              Anthony Bourdain: Parts Unknown  TV Show        NaT
6795   s6796                                      Frasier  TV Show        NaT
6806   s6807                                      Friends  TV Show        NaT
6901   s6902                              Gunslinger Girl  TV Show        NaT
7196   s7197                                     Kikoriki  TV Show        NaT
7254   s7255                          La Familia P. Luche  TV Show        NaT
7406   s7407                                        Maron  TV Show        NaT
7847   s7848                                 Red vs. Blue  TV Show        NaT
8182   s8183                 The Adventures of Figaro Pho  TV Show        NaT

insted of removing we can add them with placeholder or we can drop them 
beacause the missing values are only 10 values that is very tiny part of our whole dataset and it wont effect our data even if we remove
so i decided to replace them with placeholders

In [79]:
# replacing the missing values in date_added with placeholder
df["date_added"] = df["date_added"].fillna("2000-01-01")

In [80]:
df.date_added

0      2021-09-25
1      2021-09-24
2      2021-09-24
3      2021-09-24
4      2021-09-24
          ...
8802   2019-11-20
8803   2019-07-01
8804   2019-11-01
8805   2020-01-11
8806   2019-03-02
Name: date_added, Length: 8807, dtype: datetime64[ns]

In [81]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [83]:
# now let's check if there are any duplicate values
df.duplicated().sum()

np.int64(0)

there are no duplicates present in the netflix dateset so we completed all data cleaning process

In [86]:
# convering the clean data set to a csv
df.to_csv("cleaned_netflix_dataset.csv", index = False)